os: windows
language: cpp
env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
before_install:
  - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
  - wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxWidgets-3.1.4.7z
  - 7z x wxWidgets-3.1.4.7z -owx-src
  - mkdir wx-build
  - mkdir wx-dist
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\Common7\\Tools\\VsDevCmd.bat\" -arch=x86"
  - "cmake -G \"Ninja\" --parallel -DwxBUILD_USE_STATIC_RUNTIME=ON -DwxBUILD_SHARED=OFF -DwxBUILD_SAMPLES=OFF -DwxBUILD_DEMOS=OFF -DwxBUILD_CXX_STANDARD=17 -DwxBUILD_COMPATIBILITY=3.1 -DCMAKE_INSTALL_PREFIX=wx-dist -S wx-src -B wx-build"
  - cd wx-build
  - nmake install
