os: windows
language: cpp
install:
  - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
  - export CXX=
  - export CXX_FOR_BUILD=
  - export CC=
  - export CC_FOR_BUILD=
  - source .travis/import_vs_env.sh "call .travis/dev_cmd.bat"
  - VsDevCmd.bat -test
  - 7z x .travis/dist/wx-dist.7z

script:
  - .travis/build_fbide.sh
