# Config for windows
version = "0.5.0"
layout = "layout.toml"
locale = "locales/en.toml"
theme = "themes/classic.toml"
shortcuts = "shortcuts_win.toml"
keywords = "keywords.toml"

# ----------------------------------------------------------------------------
# Editor settings
# ----------------------------------------------------------------------------
[editor]
tabSize = 4
edgeColumn = 80
autoIndent = true
syntaxHighlight = true
lineNumbers = true
braceHighlight = true
longLine = true
whiteSpace = true
indentGuide = true
folderMargin = true
displayEOL = true
currentLine = true

# ----------------------------------------------------------------------------
# General settings
# ----------------------------------------------------------------------------
[general]
splashScreen = true

# ----------------------------------------------------------------------------
# Compiler settings
# ----------------------------------------------------------------------------
[compiler]
path = ""
compileCommand = '"<$fbc>" "<$file>"'
runCommand = '<$terminal> "<$file>" <$param>'

# ----------------------------------------------------------------------------
# Paths
# ----------------------------------------------------------------------------
[paths]
helpFile = ""

# ----------------------------------------------------------------------------
# Fbide Window
# ----------------------------------------------------------------------------
[window]
x = 521
y = 283
width = 1438
height = 866

# ----------------------------------------------------------------------------
# UI state configs
# ----------------------------------------------------------------------------
[commands]
showExitCode = false
viewResult = false

