; Config for windows
version=0.5.0
layout=layout.ini
locale=locales/en.ini
theme=themes/classic.ini
shortcuts=shortcuts_win.ini
keywords=keywords.ini

; ----------------------------------------------------------------------------
; Editor settings
; ----------------------------------------------------------------------------
[editor]
tabSize=4
edgeColumn=80
autoIndent=1
syntaxHighlight=1
lineNumbers=1
braceHighlight=1
longLine=1
whiteSpace=1
indentGuide=1
folderMargin=1
displayEOL=1
currentLine=1

; ----------------------------------------------------------------------------
; General settings
; ----------------------------------------------------------------------------
[general]
splashScreen=1

; ----------------------------------------------------------------------------
; Compiler settings
; ----------------------------------------------------------------------------
[compiler]
path=C:\Users\Albert\Developer\FreeBASIC\fbc.exe
compileCommand="<$fbc>" "<$file>"
runCommand=<$terminal> "<$file>" <$param>

; ----------------------------------------------------------------------------
; Paths
; ----------------------------------------------------------------------------
[paths]
helpFile=FB-manual-1.10.1.chm

; ----------------------------------------------------------------------------
; Fbide Window
; ----------------------------------------------------------------------------
[window]
x=521
y=283
width=1438
height=866

; ----------------------------------------------------------------------------
; UI state configs
; ----------------------------------------------------------------------------
[commands]
showExitCode=0
viewResult=1
