; FBIde configuration for Windows
version=0.5.0
theme=themes\\modern-dark.ini
locale=locales\\en.ini
shortcuts=shortcuts_win.ini
layout=layout.ini
keywords=keywords.ini
; Appearance allows enabling dark or light mode.
; However, on Windows this is horribly brokem amd looks visually ugly.
; Options are: light, dark, system or an empty value to disable.
appearance=
[window]
y=361
x=599
width=1438
height=866
[paths]
helpFile=FB-manual-1.10.1.chm
[general]
splashScreen=1
[commands]
viewResult=1
showExitCode=0
[editor]
whiteSpace=0
longLine=1
indentGuide=0
folderMargin=0
lineNumbers=1
edgeColumn=120
tabSize=4
displayEOL=0
currentLine=1
syntaxHighlight=1
braceHighlight=1
autoIndent=1
[compiler]
runCommand=<$terminal> "<$file>" <$param>
path=C:\\Users\\Albert\\Developer\\FreeBASIC\\fbc.exe
compileCommand="\"<$fbc>\" \"<$file>\""
