# wxWidgets configuration

set(FBIDE_WX_LIBS core base aui stc net)
if(WXWIN)
    list(APPEND CMAKE_PREFIX_PATH "${WXWIN}")
    find_package(wxWidgets CONFIG REQUIRED COMPONENTS ${FBIDE_WX_LIBS})
else()
    find_package(wxWidgets 3.3 COMPONENTS ${FBIDE_WX_LIBS} REQUIRED)
    include(${wxWidgets_USE_FILE})
endif ()

function(linkWxWidgets target)
    if(WXWIN)
        foreach(comp ${FBIDE_WX_LIBS})
            target_link_libraries(${target} PUBLIC wxWidgets::${comp})
        endforeach()
    else()
        target_link_libraries(${target} PUBLIC ${wxWidgets_LIBRARIES})
    endif ()
endfunction()
