//
// FBIde editor for FreeBASIC - https://freebasic.net
// Copyright (c) 2026 Albert Varaksin
// Licensed under the MIT License. See LICENSE file for details.
// https://github.com/albeva/fbide
//
#pragma once

namespace fbide {

/// Translation string identifiers.
/// Underlying values match legacy .fbl file indexes for direct import.
enum class LangId : int {
    EmptyString = 0,
    // Generic
    Welcome = 1,
    OK = 2,
    Cancel = 3,
    Message = 161,
    ConsoleLine = 165,
    ConsoleFile = 166,
    ConsoleErrorNr = 167,
    ConsoleMessage = 168,
    Untitled = 229,

    // Menu bar
    MenuFile = 4,
    MenuEdit = 5,
    MenuSearch = 6,
    MenuView = 7,
    MenuTools = 8,
    MenuRun = 9,
    MenuHelp = 10,

    // File menu
    FileNew = 11,
    FileNewHelp = 12,
    FileOpen = 13,
    FileOpenHelp = 14,
    FileSave = 15,
    FileSaveHelp = 16,
    FileSaveAs = 17,
    FileSaveAsHelp = 18,
    FileSaveAll = 19,
    FileSaveAllHelp = 20,
    FileClose = 21,
    FileCloseHelp = 22,
    FileNewWindow = 23,
    FileNewWindowHelp = 24,
    FileQuit = 25,
    FileQuitHelp = 26,
    FileSessionLoad = 169,
    FileSessionLoadHelp = 170,
    FileSessionSave = 171,
    FileSessionSaveHelp = 172,
    FileCloseAll = 173,
    FileCloseAllHelp = 174,

    // Edit menu
    EditUndo = 27,
    EditUndoHelp = 28,
    EditRedo = 29,
    EditRedoHelp = 30,
    EditCut = 31,
    EditCutHelp = 32,
    EditCopy = 33,
    EditCopyHelp = 34,
    EditPaste = 35,
    EditPasteHelp = 36,
    EditSelectAll = 37,
    EditSelectAllHelp = 38,
    EditSelectLine = 39,
    EditSelectLineHelp = 40,
    EditIndentInc = 41,
    EditIndentIncHelp = 42,
    EditIndentDec = 43,
    EditIndentDecHelp = 44,
    EditComment = 45,
    EditCommentHelp = 46,
    EditUncomment = 47,
    EditUncommentHelp = 48,

    // Search menu
    SearchFind = 49,
    SearchFindHelp = 50,
    SearchFindNext = 51,
    SearchFindNextHelp = 52,
    SearchReplace = 53,
    SearchReplaceHelp = 54,
    SearchGotoLine = 55,
    SearchGotoLineHelp = 56,

    // View menu
    ViewSettings = 57,
    ViewSettingsHelp = 58,
    ViewResult = 59,
    ViewResultHelp = 60,
    ViewSubs = 61,
    ViewSubsHelp = 62,
    ViewFormat = 175,
    ViewFormatHelp = 176,
    ViewCompilerLog = 236,
    ViewCompilerLogHelp = 237,

    // Run menu
    RunCompile = 63,
    RunCompileHelp = 64,
    RunCompileAndRun = 65,
    RunCompileAndRunHelp = 66,
    RunRun = 67,
    RunRunHelp = 68,
    RunQuickRun = 69,
    RunQuickRunHelp = 70,
    RunCmdPrompt = 71,
    RunCmdPromptHelp = 72,
    RunParameters = 73,
    RunParametersHelp = 74,
    RunShowExitCode = 77,
    RunShowExitCodeHelp = 78,
    RunActivePath = 234,
    RunActivePathHelp = 235,

    // Help menu
    HelpAbout = 79,
    HelpAboutHelp = 80,

    // Toolbar
    ToolbarNew = 83,
    ToolbarOpen = 84,
    ToolbarSave = 85,
    ToolbarSaveAll = 86,
    ToolbarClose = 87,
    ToolbarCut = 88,
    ToolbarCopy = 89,
    ToolbarPaste = 90,
    ToolbarUndo = 91,
    ToolbarRedo = 92,
    ToolbarCompile = 93,
    ToolbarRun = 94,
    ToolbarCompileAndRun = 95,
    ToolbarQuickRun = 96,
    ToolbarResult = 97,

    // Settings dialog
    SettingsTitle = 98,
    SettingsGeneral = 99,
    SettingsThemes = 100,
    SettingsKeywords = 101,
    SettingsCompiler = 102,
    SettingsLineNumbers = 103,
    SettingsEditorSettings = 104,
    SettingsBraceHighlight = 105,
    SettingsSyntaxHighlight = 106,
    SettingsRightMargin = 107,
    SettingsLineEndings = 108,
    SettingsWhitespace = 109,
    SettingsIndentGuides = 110,
    SettingsFoldMargin = 111,
    SettingsAutoIndent = 112,
    SettingsCompilerSettings = 113,
    SettingsCompilerPath = 114,
    SettingsCompilerCommand = 115,
    SettingsRightMarginWidth = 116,
    SettingsTabSize = 117,
    SettingsLanguage = 201,
    SettingsLanguageRestart = 202,
    SettingsLanguageSelect = 203,
    SettingsSplashScreen = 232,
    SettingsRunCommand = 238,
    SettingsCompilerAndPaths = 239,
    SettingsRunCmd = 240,
    SettingsHelpFile = 241,
    SettingsFreeBASIC = 242,
    SettingsHelpFileFilter = 243,
    SettingsCompilerPathError = 244,

    // Theme tab
    ThemeComments = 118,
    ThemeNumbers = 119,
    ThemeKeywords1 = 120,
    ThemeStringClosed = 121,
    ThemePreprocessor = 122,
    ThemeOperator = 123,
    ThemeIdentifier = 124,
    ThemeDate = 125,
    ThemeStringOpen = 126,
    ThemeKeywords2 = 127,
    ThemeKeywords3 = 128,
    ThemeKeywords4 = 129,
    ThemeConstant = 245,
    ThemeAsm = 246,
    ThemeCaret = 130,
    ThemeLineNumbers = 131,
    ThemeTextSelect = 132,
    ThemeBraceMatch = 133,
    ThemeBraceMismatch = 134,
    ThemeEditor = 135,
    ThemeBold = 136,
    ThemeItalic = 137,
    ThemeUnderline = 138,
    ThemeSave = 139,
    ThemeName = 140,
    ThemeCreateNew = 141,
    ThemeColors = 142,
    ThemeType = 143,
    ThemeForeground = 144,
    ThemeBackground = 145,
    ThemeFontStyle = 146,
    ThemeFont = 147,
    ThemeFontSize = 148,
    ThemeKeywordsLabel = 149,
    ThemeSelectGroup = 150,
    ThemeGroup1 = 151,
    ThemeGroup2 = 152,
    ThemeGroup3 = 153,
    ThemeGroup4 = 154,
    ThemeOpenFile = 155,
    ThemeCompilerFilter = 156,
    ThemeEnterName = 157,
    ThemeParametersTitle = 158,
    ThemeAlreadyExists = 159,
    ThemeOverwrite = 160,

    // Format dialog
    FormatType = 162,
    FormatGo = 163,
    FormatPreview = 164,

    // Run messages
    RunParamsPrompt = 177,
    RunNothingToCompile = 178,
    RunError = 179,
    RunCompileFirst = 180,
    RunCompileQuestion = 181,
    RunExecError = 182,
    RunFileModified = 183,
    RunSaveFile = 184,
    RunExitCode = 185,

    // File messages
    FileLoadTitle = 186,
    FileLoadFilter = 187,
    FileModifiedPrefix = 188,
    FileModifiedSuffix = 189,
    FileModifiedFormat = 190,
    FileModifiedTitle = 192,
    FileSaveFilter = 193,
    FileSaveFilterAny = 194,
    FileSaveTitle = 195,
    FileUseNew = 196,
    FileQuestion = 197,
    FileSessionFilter = 198,
    FileSessionSaveTitle = 199,
    FileHtmlFilter = 200,

    // About dialog
    AboutDescription = 204,
    AboutWebsite = 205,
    AboutMadeWith = 206,
    AboutCredits = 207,
    AboutProgrammers = 208,
    AboutHeadProgrammer = 209,
    AboutNetworkCode = 210,
    AboutAutoComplete = 211,
    AboutFormatting = 212,
    AboutI18n = 213,
    AboutMisc = 214,
    AboutWebmaster = 215,
    AboutSplashLogo = 216,
    AboutTesters = 217,
    AboutForgotten = 218,
    AboutLanguageFiles = 225,

    // Search dialogs
    SearchFindTitle = 219,
    SearchReplaceTitle = 220,
    SearchGotoPrompt = 221,
    SearchGotoTitle = 222,
    SearchLabel = 226,
    BrowserType = 227,
    BrowserArguments = 228,

    // View dialogs
    ViewFormatTitle = 223,
    ViewSubsTitle = 224,

    // Save prompts
    SaveChanges = 230,
    SaveBeforeExit = 231,

    // Compiler status messages
    StatusCompiling = 247,
    StatusCompileComplete = 248,
    StatusCompileFailed = 249,
    CompilerLogTitle = 250,

    // Unused / missing — free IDs available for reuse
    Missing0 = 0,
    Missing75 = 75, // was: compiler params (unused in original)
    Missing76 = 76, // was: compiler params help (unused in original)
    Missing81 = 81, // was: duplicate of FileCloseAll
    Missing82 = 82, // was: duplicate of FileCloseAllHelp
    Missing191 = 191,
    Missing233 = 233,
};

} // namespace fbide
